"""
Solace-AI Events Library.

Enterprise-grade event infrastructure for Solace-AI microservices:
- Kafka event publishing with transactional outbox pattern
- Consumer group management with offset tracking
- Dead letter queue handling with retry policies
- Comprehensive event schemas for all domains
"""

from .config import (
    TOPIC_CONFIGS,
    CompressionType,
    ConsumerGroup,
    ConsumerSettings,
    KafkaSettings,
    ProducerSettings,
    SaslMechanism,
    SecurityProtocol,
    SolaceTopic,
    TopicConfig,
    get_all_topics,
    get_dlq_topics,
    get_topic_config,
)
from .consumer import (
    AIOKafkaConsumerAdapter,
    ConsumerMetrics,
    EventConsumer,
    KafkaConsumerAdapter,
    MockKafkaConsumerAdapter,
    OffsetTracker,
    ProcessingResult,
    ProcessingStatus,
    create_consumer,
)
from .dead_letter import (
    DeadLetterHandler,
    DeadLetterRecord,
    DeadLetterStore,
    DLQStore,
    RetryPolicy,
    RetryStrategy,
    create_dead_letter_handler,
    get_dlq_topic,
)
from .postgres_stores import (
    PostgresDLQStore,
    PostgresOutboxStore,
)
from .publisher import (
    AIOKafkaProducerAdapter,
    EventPublisher,
    InMemoryOutboxStore,
    KafkaProducerAdapter,
    MockKafkaProducerAdapter,
    OutboxPoller,
    OutboxRecord,
    OutboxStatus,
    OutboxStore,
    create_publisher,
)
from .schemas import (
    EVENT_REGISTRY,
    AssessmentCompletedEvent,
    BaseEvent,
    ClinicalHypothesis,
    Confidence,
    ConsentChangedKafkaEvent,
    ContextAssembledEvent,
    CrisisDetectedEvent,
    CrisisLevel,
    CrisisResolvedEvent,
    DiagnosisCompletedEvent,
    ErrorOccurredEvent,
    EscalationAcknowledgedEvent,
    EscalationResolvedEvent,
    EscalationTriggeredEvent,
    EventMetadata,
    HomeworkAssignedEvent,
    IncidentCreatedEvent,
    IncidentResolvedEvent,
    InterventionDeliveredEvent,
    MemoryConsolidatedEvent,
    MemoryDecayedEvent,
    MemoryRetrievedEvent,
    MemoryStoredEvent,
    MemoryTier,
    MessageReceivedEvent,
    NotificationDeliveredKafkaEvent,
    NotificationFailedKafkaEvent,
    NotificationSentKafkaEvent,
    OceanScores,
    OutputFilteredEvent,
    PersonalityAssessedEvent,
    PersonalityProfileUpdatedEvent,
    PersonalityTraitChangedEvent,
    ProgressMilestoneEvent,
    ResponseGeneratedEvent,
    RetentionCategory,
    RiskFactor,
    RiskLevelChangedEvent,
    SafetyAssessmentEvent,
    SafetyPlanActivatedEvent,
    SafetyPlanCreatedEvent,
    SafetyPlanUpdatedEvent,
    SessionEndedEvent,
    SessionStartedEvent,
    StyleGeneratedEvent,
    SystemHealthEvent,
    TherapyModality,
    TherapySessionStartedEvent,
    TrajectoryAlertEvent,
    TreatmentResponseEvent,
    UserCreatedKafkaEvent,
    UserDeletedKafkaEvent,
    deserialize_event,
    get_topic_for_event,
)

__all__ = [
    # Config
    "CompressionType",
    "ConsumerGroup",
    "ConsumerSettings",
    "KafkaSettings",
    "ProducerSettings",
    "SaslMechanism",
    "SecurityProtocol",
    "SolaceTopic",
    "TopicConfig",
    "TOPIC_CONFIGS",
    "get_all_topics",
    "get_dlq_topics",
    "get_topic_config",
    # Publisher
    "AIOKafkaProducerAdapter",
    "EventPublisher",
    "InMemoryOutboxStore",
    "KafkaProducerAdapter",
    "MockKafkaProducerAdapter",
    "OutboxPoller",
    "OutboxRecord",
    "OutboxStatus",
    "OutboxStore",
    "create_publisher",
    # Consumer
    "AIOKafkaConsumerAdapter",
    "ConsumerMetrics",
    "EventConsumer",
    "KafkaConsumerAdapter",
    "MockKafkaConsumerAdapter",
    "OffsetTracker",
    "ProcessingResult",
    "ProcessingStatus",
    "create_consumer",
    # Dead Letter
    "DeadLetterHandler",
    "DeadLetterRecord",
    "DeadLetterStore",
    "DLQStore",
    "RetryPolicy",
    "RetryStrategy",
    "create_dead_letter_handler",
    "get_dlq_topic",
    # Postgres Stores
    "PostgresDLQStore",
    "PostgresOutboxStore",
    # Schemas - Base
    "BaseEvent",
    "EventMetadata",
    "EVENT_REGISTRY",
    "deserialize_event",
    "get_topic_for_event",
    # Schemas - Session
    "SessionStartedEvent",
    "SessionEndedEvent",
    "MessageReceivedEvent",
    "ResponseGeneratedEvent",
    # Schemas - Safety
    "CrisisLevel",
    "RiskFactor",
    "SafetyAssessmentEvent",
    "CrisisDetectedEvent",
    "CrisisResolvedEvent",
    "EscalationTriggeredEvent",
    "EscalationAcknowledgedEvent",
    "EscalationResolvedEvent",
    "RiskLevelChangedEvent",
    "IncidentCreatedEvent",
    "IncidentResolvedEvent",
    "SafetyPlanCreatedEvent",
    "SafetyPlanActivatedEvent",
    "SafetyPlanUpdatedEvent",
    "OutputFilteredEvent",
    "TrajectoryAlertEvent",
    # Schemas - Diagnosis
    "Confidence",
    "ClinicalHypothesis",
    "DiagnosisCompletedEvent",
    "AssessmentCompletedEvent",
    # Schemas - Therapy
    "TherapyModality",
    "TherapySessionStartedEvent",
    "InterventionDeliveredEvent",
    "ProgressMilestoneEvent",
    # Schemas - Memory
    "MemoryTier",
    "RetentionCategory",
    "MemoryStoredEvent",
    "MemoryConsolidatedEvent",
    "MemoryRetrievedEvent",
    "MemoryDecayedEvent",
    "ContextAssembledEvent",
    # Schemas - Personality
    "OceanScores",
    "PersonalityAssessedEvent",
    "StyleGeneratedEvent",
    "PersonalityProfileUpdatedEvent",
    "PersonalityTraitChangedEvent",
    # Schemas - Notification
    "NotificationSentKafkaEvent",
    "NotificationDeliveredKafkaEvent",
    "NotificationFailedKafkaEvent",
    # Schemas - User
    "UserCreatedKafkaEvent",
    "UserDeletedKafkaEvent",
    "ConsentChangedKafkaEvent",
    # Schemas - System
    "SystemHealthEvent",
    "ErrorOccurredEvent",
    # Schemas - Homework & Treatment
    "HomeworkAssignedEvent",
    "TreatmentResponseEvent",
]
