"""Solace-AI Infrastructure Library - Database clients, caching, and observability utilities."""
from solace_infrastructure.postgres import (
    PostgresClient,
    PostgresRepository,
    PostgresSettings,
    IsolationLevel,
    QueryResult,
    create_postgres_client,
)
from solace_infrastructure.redis import (
    RedisClient,
    RedisSettings,
    RedisMode,
    CacheEntry,
    create_redis_client,
)
from solace_infrastructure.weaviate import (
    WeaviateClient,
    WeaviateSettings,
    CollectionConfig,
    PropertyConfig,
    PropertyDataType,
    VectorDistanceMetric,
    SearchResult,
    create_weaviate_client,
)
from solace_infrastructure.health import (
    HealthMonitor,
    HealthChecker,
    ClientHealthChecker,
    CallableHealthChecker,
    HealthCheckResult,
    ComponentHealth,
    HealthStatus,
    ComponentType,
    HealthCheckable,
    create_health_monitor,
)
from solace_infrastructure.observability import (
    ObservabilitySettings,
    LogLevel,
    MetricType,
    MetricValue,
    MetricsRegistry,
    Span,
    Tracer,
    configure_logging,
    get_correlation_id,
    set_correlation_id,
    get_trace_context,
    set_trace_context,
    add_log_context,
    get_metrics_registry,
    get_tracer,
    traced,
    timed,
    counted,
)

__all__ = [
    # PostgreSQL
    "PostgresClient",
    "PostgresRepository",
    "PostgresSettings",
    "IsolationLevel",
    "QueryResult",
    "create_postgres_client",
    # Redis
    "RedisClient",
    "RedisSettings",
    "RedisMode",
    "CacheEntry",
    "create_redis_client",
    # Weaviate
    "WeaviateClient",
    "WeaviateSettings",
    "CollectionConfig",
    "PropertyConfig",
    "PropertyDataType",
    "VectorDistanceMetric",
    "SearchResult",
    "create_weaviate_client",
    # Health
    "HealthMonitor",
    "HealthChecker",
    "ClientHealthChecker",
    "CallableHealthChecker",
    "HealthCheckResult",
    "ComponentHealth",
    "HealthStatus",
    "ComponentType",
    "HealthCheckable",
    "create_health_monitor",
    # Observability
    "ObservabilitySettings",
    "LogLevel",
    "MetricType",
    "MetricValue",
    "MetricsRegistry",
    "Span",
    "Tracer",
    "configure_logging",
    "get_correlation_id",
    "set_correlation_id",
    "get_trace_context",
    "set_trace_context",
    "add_log_context",
    "get_metrics_registry",
    "get_tracer",
    "traced",
    "timed",
    "counted",
]
