"""Solace-AI Infrastructure Library - Database clients, caching, and observability utilities."""
from solace_infrastructure.kafka import (
    # Topics
    CleanupPolicy,
    CompressionCodec,
    TimestampType,
    TopicPriority,
    TopicDefinition,
    TopicAdminSettings,
    TopicMetadata,
    TopicOperationResult,
    TopicValidator,
    KafkaAdminAdapter,
    TopicManager,
    create_topic_manager,
    # Schemas
    SchemaType,
    CompatibilityLevel,
    SchemaFormat,
    SchemaVersion,
    SchemaMetadata,
    CompatibilityResult,
    SchemaRegistrySettings,
    SchemaDefinition,
    SchemaValidator,
    JsonSchemaValidator,
    AvroSchemaValidator,
    SchemaCache,
    SchemaRegistryAdapter,
    SchemaManager,
    create_schema_manager,
    # Partitioning
    PartitionStrategy,
    PartitionResult,
    PartitionerConfig,
    Partitioner,
    RoundRobinPartitioner,
    HashKeyPartitioner,
    UserAffinityPartitioner,
    PriorityPartitioner,
    StickyPartitioner,
    PartitionerFactory,
    TopicPartitionRouter,
    create_partition_router,
    # Retention
    RetentionType,
    ComplianceCategory,
    RetentionPriority,
    RetentionMetrics,
    RetentionPolicy,
    TopicRetentionAssignment,
    RetentionManager,
    PRESET_POLICIES,
    create_retention_manager,
    get_hipaa_policy,
    # Monitoring
    AlertSeverity,
    BrokerMetrics,
    TopicMetrics as KafkaTopicMetrics,
    ConsumerGroupMetrics,
    ConsumerLag,
    KafkaAlert,
    ClusterHealth,
    MonitoringSettings,
    MetricsCollector,
    KafkaMonitorAdapter,
    KafkaMonitor,
    create_kafka_monitor,
)
from solace_infrastructure.postgres import (
    PostgresClient,
    PostgresRepository,
    PostgresSettings,
    IsolationLevel,
    QueryResult,
    create_postgres_client,
)
from solace_infrastructure.redis import (
    RedisClient,
    RedisSettings,
    RedisMode,
    CacheEntry,
    create_redis_client,
)
from solace_infrastructure.weaviate import (
    WeaviateClient,
    WeaviateSettings,
    CollectionConfig,
    PropertyConfig,
    PropertyDataType,
    VectorDistanceMetric,
    SearchResult,
    create_weaviate_client,
)
from solace_infrastructure.health import (
    HealthMonitor,
    HealthChecker,
    ClientHealthChecker,
    CallableHealthChecker,
    HealthCheckResult,
    ComponentHealth,
    HealthStatus,
    ComponentType,
    HealthCheckable,
    create_health_monitor,
)
from solace_infrastructure.observability import (
    ObservabilitySettings,
    LogLevel,
    MetricType,
    MetricValue,
    MetricsRegistry,
    Span,
    Tracer,
    configure_logging,
    get_correlation_id,
    set_correlation_id,
    get_trace_context,
    set_trace_context,
    add_log_context,
    get_metrics_registry,
    get_tracer,
    traced,
    timed,
    counted,
)
from solace_infrastructure.database import (
    # Base models
    Base,
    BaseModel as DBBaseModel,
    AuditableModel,
    TenantModel,
    TimestampMixin,
    SoftDeleteMixin,
    VersionMixin,
    AuditMixin,
    TenantMixin,
    ModelState,
    create_all_tables,
    create_all_tables_async,
    # Migrations
    MigrationRunner,
    MigrationSettings,
    MigrationDirection,
    MigrationState,
    MigrationInfo,
    MigrationResult,
    create_migration_runner,
    # Seed data
    SeedDataLoader,
    SeedSettings,
    SeedResult,
    SeedCategory,
    Environment,
    create_seed_loader,
    # Weaviate schema
    WeaviateSchemaManager,
    WeaviateSchemaSettings,
    SolaceCollections,
    CollectionDefinition,
    CollectionType,
    setup_weaviate_schema,
    # Redis setup
    RedisSetupManager,
    RedisSetupSettings,
    RedisKeyBuilder,
    RedisNamespace,
    MemoryTier,
    TTLPolicy,
    setup_redis,
)

__all__ = [
    # Kafka Topics
    "CleanupPolicy",
    "CompressionCodec",
    "TimestampType",
    "TopicPriority",
    "TopicDefinition",
    "TopicAdminSettings",
    "TopicMetadata",
    "TopicOperationResult",
    "TopicValidator",
    "KafkaAdminAdapter",
    "TopicManager",
    "create_topic_manager",
    # Kafka Schemas
    "SchemaType",
    "CompatibilityLevel",
    "SchemaFormat",
    "SchemaVersion",
    "SchemaMetadata",
    "CompatibilityResult",
    "SchemaRegistrySettings",
    "SchemaDefinition",
    "SchemaValidator",
    "JsonSchemaValidator",
    "AvroSchemaValidator",
    "SchemaCache",
    "SchemaRegistryAdapter",
    "SchemaManager",
    "create_schema_manager",
    # Kafka Partitioning
    "PartitionStrategy",
    "PartitionResult",
    "PartitionerConfig",
    "Partitioner",
    "RoundRobinPartitioner",
    "HashKeyPartitioner",
    "UserAffinityPartitioner",
    "PriorityPartitioner",
    "StickyPartitioner",
    "PartitionerFactory",
    "TopicPartitionRouter",
    "create_partition_router",
    # Kafka Retention
    "RetentionType",
    "ComplianceCategory",
    "RetentionPriority",
    "RetentionMetrics",
    "RetentionPolicy",
    "TopicRetentionAssignment",
    "RetentionManager",
    "PRESET_POLICIES",
    "create_retention_manager",
    "get_hipaa_policy",
    # Kafka Monitoring
    "AlertSeverity",
    "BrokerMetrics",
    "KafkaTopicMetrics",
    "ConsumerGroupMetrics",
    "ConsumerLag",
    "KafkaAlert",
    "ClusterHealth",
    "MonitoringSettings",
    "MetricsCollector",
    "KafkaMonitorAdapter",
    "KafkaMonitor",
    "create_kafka_monitor",
    # PostgreSQL
    "PostgresClient",
    "PostgresRepository",
    "PostgresSettings",
    "IsolationLevel",
    "QueryResult",
    "create_postgres_client",
    # Redis
    "RedisClient",
    "RedisSettings",
    "RedisMode",
    "CacheEntry",
    "create_redis_client",
    # Weaviate
    "WeaviateClient",
    "WeaviateSettings",
    "CollectionConfig",
    "PropertyConfig",
    "PropertyDataType",
    "VectorDistanceMetric",
    "SearchResult",
    "create_weaviate_client",
    # Health
    "HealthMonitor",
    "HealthChecker",
    "ClientHealthChecker",
    "CallableHealthChecker",
    "HealthCheckResult",
    "ComponentHealth",
    "HealthStatus",
    "ComponentType",
    "HealthCheckable",
    "create_health_monitor",
    # Observability
    "ObservabilitySettings",
    "LogLevel",
    "MetricType",
    "MetricValue",
    "MetricsRegistry",
    "Span",
    "Tracer",
    "configure_logging",
    "get_correlation_id",
    "set_correlation_id",
    "get_trace_context",
    "set_trace_context",
    "add_log_context",
    "get_metrics_registry",
    "get_tracer",
    "traced",
    "timed",
    "counted",
    # Database - Base Models
    "Base",
    "DBBaseModel",
    "AuditableModel",
    "TenantModel",
    "TimestampMixin",
    "SoftDeleteMixin",
    "VersionMixin",
    "AuditMixin",
    "TenantMixin",
    "ModelState",
    "create_all_tables",
    "create_all_tables_async",
    # Database - Migrations
    "MigrationRunner",
    "MigrationSettings",
    "MigrationDirection",
    "MigrationState",
    "MigrationInfo",
    "MigrationResult",
    "create_migration_runner",
    # Database - Seed Data
    "SeedDataLoader",
    "SeedSettings",
    "SeedResult",
    "SeedCategory",
    "Environment",
    "create_seed_loader",
    # Database - Weaviate Schema
    "WeaviateSchemaManager",
    "WeaviateSchemaSettings",
    "SolaceCollections",
    "CollectionDefinition",
    "CollectionType",
    "setup_weaviate_schema",
    # Database - Redis Setup
    "RedisSetupManager",
    "RedisSetupSettings",
    "RedisKeyBuilder",
    "RedisNamespace",
    "MemoryTier",
    "TTLPolicy",
    "setup_redis",
]
